  vars:
    resource_group: jlgf-resource_group
    location: uksouth
    registry_name: containerRegistryjlgf
    repo_url: "git@github.com:joseluisgfj/AZ_practica2.git"
    workspace: /home/practica2/ansible_workspace/
    image_name: apache_01
    http_port: 443
    email: joseluis.gonzalez035@comunidadunir.net
  tasks:
    - name: Git Clone
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workspace }}"
        clone: yes
        update: yes

    - name: Login docker registry
      docker_login:
        registry: "{{ registry_name }}.azurecr.io"
        username: "{{ registry_name }}"
        password: LVDA2If9TU6zD7Q66Pkz3SsdEdamGa4EqciMMzbveK+ACRBk1gm+
        email: "{{ email }}"

    - name: Docker Build and Push
      docker_image:
        path: "{{ workspace }}"
        name: "{{ registry_name }}.azurecr.io/{{ image_name }}"
        push: yes

    - name:  deploy apache_01 on container
       hosts: vm01
       become: true
       gather_facts: false

    - name: podman installed
      ansible.builtin.yum:
       name: podman
       state: latest
     
    - name: pull image
      containers.podman.podman_image:
       name: "{{ image_name }}"
       pull: true
       username: FALTAAAAA
       password: FALTAAAAA
       tag: latest
   
    - name: run apache_01 container
      containers.podman.podman_container:
       name: webserver
       image: "{{ image_name }}"
       state: started
       detach: true
       expose:
        - 443
       ports:
        - 8080:80
